# Generated by Django 3.0.7 on 2020-06-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('ugv', 'ugv'), ('uav', 'uav'), ('usv', 'usv'), ('uuv', 'uuv')], max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('free', 'free'), ('busy', 'busy')], default='free', max_length=10)),
                ('isAvailable', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
